<?xml version="1.0" encoding="utf-8"?>
<Database Name="StudentDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=vm2k3s;Initial Catalog=StudentDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StudentDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudentInfo" Member="StudentInfo">
    <Type Name="StudentInfo">
      <Column Name="StudentID" Type="System.String" DbType="Char(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Specialty" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>